import Head from 'next/head'
import React from 'react'
import styles from '../styles/Home.module.css'
import Login from './Login'


const Home = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>My App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Login />
    </div>
  )
}


export default Home

